export const ZONES = [
    "ZONA 1",
    "ZONA 2",
    "ZONA 3",
    "ZONA 4",
    "ZONA 5",
    "ZONA 6",
    "ZONA 7",
    "ZONA 8",
    "ZONA 9",
    "ZONA 10",
    "ZONA 11",
    "ZONA 12",
    "ZONA 13",
    "ZONA 14",
    "ZONA 15",
    "ZONA 16",
    "ZONA 17",
    "ZONA 18",
    "ZONA 19",
    "ZONA 20",
] as const